### ISSUE TITLE
Refactor news items on main page

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [roodjong/roodjongeren#23]
Sent in via email:

- Er moet een extra kolom op de homepage komen voor opiniestukken/inzendingen
- Er moet een manier zijn om nieuwsberichten wel of niet op de homepagina te laten verschijnen. Zodat we vooral landelijke berichten op de homepage krijgen.

Second point is probably easiest to implement with some kind of checkbox on each post.

**Comment by Martionex** [comment]
Idee van Robin en mij: i.p.v. een boolean switch een tag-systeem waarin een landelijke post bvb "nieuwsbericht" en "landelijk" als tags heeft.

**Comment by AndrewAmmerlaan** [comment]
> Idee van Robin en mij: i.p.v. een boolean switch een tag-systeem waarin een landelijke post bvb "nieuwsbericht" en "landelijk" als tags heeft.

Lijkt me ook prima, maar ik zou de tag 'voorpagina' noemen ipv 'landelijk', want soms wil je misschien ook een lokale post uitlichten op de voorpagina.
