### ISSUE TITLE
Automatisch default afbeelding aan een websitebericht toevoegen.

### ISSUE THREAD

**Issue by Bogaardtiesvd** [roodjong/roodjongeren#33]
Op dit moment zie je op het overzicht van websiteberichten dat sommige berichten wel een afbeelding hebben en sommige niet. Als het mogelijk is zou het goed zijn een default image aan te wijzen zodat als men het vergeet het niet een kale plek is tussen andere berichten

![Knipsel](https://user-images.githubusercontent.com/108726138/177292350-059a92f0-a7df-4158-8329-b2f447964ad3.PNG)
.

**Comment by Martionex** [comment]
Zou het ROOD-logo kunnen zijn in banner-formaat

**Comment by AndrewAmmerlaan** [comment]
> Zou het ROOD-logo kunnen zijn in banner-formaat

Lijkt me voor nu prima.

Voor in de toekomst zouden we ook iets fancy's kunnen doen zoals een random afbeelding pakken uit een selectie van toffe banner foto's zodat niet alle posts precies dezelfde default afbeelding hebben.

**Comment by AndrewAmmerlaan** [comment]
> Op dit moment zie je op het overzicht van websiteberichten dat sommige berichten wel een afbeelding hebben en sommige niet. Als het mogelijk is zou het goed zijn een default image aan te wijzen zodat als men het vergeet het niet een kale plek is tussen andere berichten
> 
> ![Knipsel](https://user-images.githubusercontent.com/108726138/177292350-059a92f0-a7df-4158-8329-b2f447964ad3.PNG) .

![image](https://user-images.githubusercontent.com/8460628/177521590-1c2ec462-6c88-4b1a-a87a-8b52a06fd5c9.png)

Thoughts? Waar er "artikel-banner" staat komt de banner die specifiek bij dat artikel hoort, die heb ik niet op mijn lokale kopie staan dus die ontbreken in de screenshot.
