### ISSUE TITLE
Foto's zijn steeds te groot

### ISSUE THREAD

**Issue by KenHesselink** [roodjong/roodjongeren#39]
Foto's zijn steeds te groot om te uploaden. Dit is best irritant en was geen probleem op de vorige website. Als ik een website gebruik om te compressen is het vaak nog steeds te groot. Dus nu doe ik maar screenshots maken van de foto's en die uploaden, maar dat lijkt me ook niet de bedoeling.

Verder heel mooie site! Ik vind specifiek de opmaak van de kopjes ook heel leuk.

**Comment by AndrewAmmerlaan** [comment]
@pingiun Deze had jij al opgelost als ik me goed herinner, toch?

**Comment by pingiun** [comment]
Jup dit is opgelost!
