### ISSUE TITLE
Feature request: doorverwijslinkjes systeem

### ISSUE THREAD

**Issue by MarcelBostelaar** [roodjong/roodjongeren#41]
Hoi,

Zouden jullie een doorverwijslinkjesystseem willen opzetten?

Feature: Groepen/leden kunnen een link aanmaken op de rood site, die als je er naar toe gaat, doorlinken naar een andere link die op elk moment aangepast kan worden. Link kan in daarvoor gemaakt subdomein staan zoals roodjongeren.nl/links/jouwURLhier

Use case: Het aanmaken van een URL om een QR code van te maken, waarbij de QR code gelijk kan blijven maar je de achterliggende link kan veranderen, voor bijvoorbeeld acties waarbij zo vroeg mogelijk geprint moet worden, hetbruiken van QR code stickers, veranderen van verwoording orignele URL. Aanleiding was een actie waarin we nog geen QR code hadden voor de drukker, en spoedkosten moesten bijbetalen, omdat het artikel nog niet live was.

Should have: 
* makkelijk aanmaakbaar en aanpasbaar voor groepen zelf? Simpel CRUDje
* Link is niet randomly generated maar zelf in te voeren door groepen zodat de link er niet helemaal sketchy uit ziet

Would like: 
* Statistiek per dag van aantal benaderingen, in graph vorm. Kan je zien hoe effectief je actie is.

**Comment by AndrewAmmerlaan** [comment]
@pingiun Jij had al zoeits gemaakt right? Wat is de status daarvan?

**Comment by pingiun** [comment]
Dit is hoe het er nu uit ziet:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1576660/185885192-f08b84b4-9025-41a9-8648-82cd1c50bd90.png">

**Comment by AndrewAmmerlaan** [comment]
Mischien dat we op termijn een menutje kunnen maken in de strapi backend voor het manangen van simpele redirect rules naar externe paginas. Plus dan een redirect vanuit jong.red naar roodjongeren.nl voor nog kortere urls.

**Comment by AndrewAmmerlaan** [comment]
See also: https://github.com/roodjong/mijnrood/issues/44

**Comment by Martionex** [comment]
Closed omdat jong.red al bestaat hiervoor
