### ISSUE TITLE
Doorverwijzen naar socialisten.org bij inschrijven

### ISSUE THREAD

**Issue by MarcelBostelaar** [roodjong/roodjongeren#45]
Op dit moment wordt socialisten niet genoemd. Bij "wordt lid" is enkel steunlidmaatschap aangegeven, maar niet lidmaatschap van socialisten.

**Comment by AndrewAmmerlaan** [comment]
@Bogaardtiesvd Thoughts?

**Comment by Martionex** [comment]
Probleem is dat de Socialisten nog geen ledenadministratiesysteem heeft.
Wel kan het bestuur de Steun Ons-pagina zelf aanpassen via Strapi, en een link naar Socialisten.org erin plaatsen.

**Comment by Martionex** [comment]
Closed omdat ze nog geen ledensysteem hebben, en daarbij kan de link geplaatst worden door iemand met bewerkrechten op de Word-lid- en Steun-ons-pagina's
